/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    'team-members': TeamMember;
    'blog-categories': BlogCategory;
    'blog-posts': BlogPost;
    reviews: Review;
    faqs: Faq;
    inquiries: Inquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    homepage: Homepage;
    'about-page': AboutPage;
    'contact-page': ContactPage;
    'legal-content': LegalContent;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'legal-content': LegalContentSelect<false> | LegalContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for visitors using screen readers. Leave empty only when the image is decorative.
   */
  alt?: string | null;
  decorative?: boolean | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * The public URL segment for this record. Lowercase letters, numbers and hyphens.
   */
  slug: string;
  /**
   * Shown on service cards and index pages.
   */
  shortDescription: string;
  /**
   * Main headline shown at the top of the service page.
   */
  heroTitle: string;
  /**
   * Supporting sentence under the headline.
   */
  heroLead?: string | null;
  /**
   * Optional image for the hero. Public website imagery only.
   */
  heroImage?: (number | null) | Media;
  explanationHeading?: string | null;
  /**
   * Plain-language explanation of the service.
   */
  explanationContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  audiencesHeading?: string | null;
  audiences?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  benefitsHeading?: string | null;
  benefits?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  processHeading?: string | null;
  processSteps?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Show this service in the featured section on the homepage.
   */
  featured?: boolean | null;
  featuredHeadline?: string | null;
  featuredContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Other services shown at the bottom of this page.
   */
  relatedServices?: (number | Service)[] | null;
  /**
   * Lower numbers appear first.
   */
  displayOrder?: number | null;
  seo?: {
    /**
     * Recommended up to 60 characters. Leave empty to use the page title.
     */
    title?: string | null;
    /**
     * Recommended up to 160 characters. Leave empty to use a sensible fallback.
     */
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  /**
   * Exact, verified role only (for example "Owner, Nusra Trading Inc").
   */
  role?: string | null;
  photo?: (number | null) | Media;
  bio?: string | null;
  /**
   * Optional public phone number.
   */
  phone?: string | null;
  /**
   * Optional public email address.
   */
  email?: string | null;
  /**
   * Only publish credentials confirmed with the client.
   */
  credentials?:
    | {
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  languages?:
    | {
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  title: string;
  /**
   * The public URL segment for this record. Lowercase letters, numbers and hyphens.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * The public URL segment for this record. Lowercase letters, numbers and hyphens.
   */
  slug: string;
  /**
   * Short summary shown on the blog index and at the top of the article.
   */
  excerpt: string;
  featuredImage?: (number | null) | Media;
  category?: (number | null) | BlogCategory;
  /**
   * Optional. Falls back to the site name when empty.
   */
  author?: (number | null) | TeamMember;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Services promoted at the end of the article.
   */
  relatedServices?: (number | Service)[] | null;
  /**
   * Used for sorting and display. Articles with future dates are treated as drafts.
   */
  publishedAt: string;
  /**
   * Optional "last updated" date shown on the article.
   */
  updatedAtOverride?: string | null;
  seo?: {
    /**
     * Recommended up to 60 characters. Leave empty to use the page title.
     */
    title?: string | null;
    /**
     * Recommended up to 160 characters. Leave empty to use a sensible fallback.
     */
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  authorName: string;
  serviceReceived?: string | null;
  reviewText: string;
  /**
   * For example "Google" or "Facebook".
   */
  sourceName?: string | null;
  /**
   * Link to the original review, when available.
   */
  sourceUrl?: string | null;
  /**
   * Only published reviews appear on the public site.
   */
  published?: boolean | null;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  /**
   * Only published FAQs appear on the public site.
   */
  published?: boolean | null;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact-request inquiries submitted through the public form. Do not enter Social Security numbers, passport numbers, tax documents, immigration documents, banking details, or other highly sensitive personal information here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  service: number | Service;
  /**
   * Service title at the time of submission.
   */
  serviceLabelSnapshot?: string | null;
  preferredContactMethod: 'phone' | 'whatsapp' | 'email';
  /**
   * Optional message. Warns visitors not to send sensitive information.
   */
  message?: string | null;
  /**
   * Server-controlled submission timestamp.
   */
  submittedAt: string;
  /**
   * Server-controlled consent timestamp.
   */
  consentAt: string;
  status: 'New' | 'Contacted' | 'Closed';
  /**
   * Server-controlled notification status.
   */
  notificationEmailStatus: 'Pending' | 'Sent' | 'Failed';
  /**
   * Sanitized provider error when the notification email failed.
   */
  notificationError?: string | null;
  /**
   * HMAC fingerprint used for rate limiting. Never contains a raw IP address.
   */
  rateLimitFingerprint?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  decorative?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  heroTitle?: T;
  heroLead?: T;
  heroImage?: T;
  explanationHeading?: T;
  explanationContent?: T;
  audiencesHeading?: T;
  audiences?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  benefitsHeading?: T;
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  processHeading?: T;
  processSteps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  featured?: T;
  featuredHeadline?: T;
  featuredContent?: T;
  relatedServices?: T;
  displayOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  bio?: T;
  phone?: T;
  email?: T;
  credentials?:
    | T
    | {
        label?: T;
        id?: T;
      };
  languages?:
    | T
    | {
        label?: T;
        id?: T;
      };
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  category?: T;
  author?: T;
  content?: T;
  relatedServices?: T;
  publishedAt?: T;
  updatedAtOverride?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  authorName?: T;
  serviceReceived?: T;
  reviewText?: T;
  sourceName?: T;
  sourceUrl?: T;
  published?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  published?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  service?: T;
  serviceLabelSnapshot?: T;
  preferredContactMethod?: T;
  message?: T;
  submittedAt?: T;
  consentAt?: T;
  status?: T;
  notificationEmailStatus?: T;
  notificationError?: T;
  rateLimitFingerprint?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Business details shown across the site. Changes appear immediately — no publishing workflow needed for contact information.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  businessName: string;
  /**
   * Shown in the footer and legal pages.
   */
  legalBusinessName: string;
  /**
   * Year the business was established, shown in the trust strip.
   */
  sinceYear?: string | null;
  /**
   * Primary phone, shown in the header, footer and CTAs.
   */
  phone: string;
  /**
   * WhatsApp number (digits only, with country code) used for wa.me links.
   */
  whatsApp: string;
  publicEmail: string;
  /**
   * Where new inquiry notifications are sent.
   */
  inquiryNotificationEmail: string;
  street: string;
  city: string;
  state: string;
  zip: string;
  /**
   * Google Maps (or similar) directions link for the office.
   */
  directionsUrl?: string | null;
  /**
   * For example "Cash, Zelle, Visa and Mastercard".
   */
  paymentsAccepted?: string | null;
  /**
   * Leave empty until hours are confirmed. The site hides this section when empty.
   */
  officeHours?:
    | {
        days: string;
        hours: string;
        id?: string | null;
      }[]
    | null;
  /**
   * For example "Walk-ins welcome, appointments optional".
   */
  walkInsNote?: string | null;
  /**
   * Spoken-language labels shown in the header/hero. No nationality flags.
   */
  languages?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  requestAssistanceLabel?: string | null;
  callNowLabel?: string | null;
  whatsAppLabel?: string | null;
  getDirectionsLabel?: string | null;
  /**
   * Verified credentials only (e.g. "Authorized IRS e-file Provider"). Keep empty until wording is confirmed with the client.
   */
  verifiedCredentialLabels?:
    | {
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional short line shown above the legal disclaimer in the footer.
   */
  footerText?: string | null;
  /**
   * Only verified public profiles. Keep empty when there are no active profiles.
   */
  socialLinks?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  heroHeadline: string;
  heroSupportingCopy: string;
  /**
   * Real approved photography only — no stock placeholders.
   */
  heroImage?: (number | null) | Media;
  servicesHeading: string;
  servicesIntro?: string | null;
  /**
   * Services shown as cards. Leave empty to show all published services.
   */
  services?: (number | Service)[] | null;
  whyChooseUsHeading: string;
  whyChooseUs?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  whoWeHelpHeading: string;
  whoWeHelp?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional featured/seasonal service. Section is hidden when empty.
   */
  featuredService?: (number | null) | Service;
  featuredHeadline?: string | null;
  featuredBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  teamHeading: string;
  /**
   * Optional. Section is hidden when empty.
   */
  teamMembers?: (number | TeamMember)[] | null;
  reviewsHeading: string;
  /**
   * Optional. Section is hidden when empty.
   */
  reviews?: (number | Review)[] | null;
  howItWorksHeading: string;
  howItWorksSteps?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  faqsHeading: string;
  /**
   * Optional. Section is hidden when empty.
   */
  faqs?: (number | Faq)[] | null;
  finalCtaHeadline: string;
  finalCtaCopy?: string | null;
  seo?: {
    /**
     * Recommended up to 60 characters. Leave empty to use the page title.
     */
    title?: string | null;
    /**
     * Recommended up to 160 characters. Leave empty to use a sensible fallback.
     */
    description?: string | null;
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  headline: string;
  lead: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  ownerName: string;
  ownerRole?: string | null;
  ownerPhoto?: (number | null) | Media;
  establishedYear?: string | null;
  serviceArea?: string | null;
  credentialsHeading?: string | null;
  /**
   * Verified credentials only.
   */
  credentials?:
    | {
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Recommended up to 60 characters. Leave empty to use the page title.
     */
    title?: string | null;
    /**
     * Recommended up to 160 characters. Leave empty to use a sensible fallback.
     */
    description?: string | null;
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  headline: string;
  lead?: string | null;
  /**
   * Short text above the request-assistance form.
   */
  formIntro?: string | null;
  seo?: {
    /**
     * Recommended up to 60 characters. Leave empty to use the page title.
     */
    title?: string | null;
    /**
     * Recommended up to 160 characters. Leave empty to use a sensible fallback.
     */
    description?: string | null;
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Client-review copy. Content here is general information, not legal advice. Do not display an attorney-review claim.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-content".
 */
export interface LegalContent {
  id: number;
  privacyPolicy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  terms?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  disclaimer?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  businessName?: T;
  legalBusinessName?: T;
  sinceYear?: T;
  phone?: T;
  whatsApp?: T;
  publicEmail?: T;
  inquiryNotificationEmail?: T;
  street?: T;
  city?: T;
  state?: T;
  zip?: T;
  directionsUrl?: T;
  paymentsAccepted?: T;
  officeHours?:
    | T
    | {
        days?: T;
        hours?: T;
        id?: T;
      };
  walkInsNote?: T;
  languages?:
    | T
    | {
        label?: T;
        id?: T;
      };
  requestAssistanceLabel?: T;
  callNowLabel?: T;
  whatsAppLabel?: T;
  getDirectionsLabel?: T;
  verifiedCredentialLabels?:
    | T
    | {
        label?: T;
        id?: T;
      };
  footerText?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroHeadline?: T;
  heroSupportingCopy?: T;
  heroImage?: T;
  servicesHeading?: T;
  servicesIntro?: T;
  services?: T;
  whyChooseUsHeading?: T;
  whyChooseUs?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  whoWeHelpHeading?: T;
  whoWeHelp?:
    | T
    | {
        label?: T;
        id?: T;
      };
  featuredService?: T;
  featuredHeadline?: T;
  featuredBody?: T;
  teamHeading?: T;
  teamMembers?: T;
  reviewsHeading?: T;
  reviews?: T;
  howItWorksHeading?: T;
  howItWorksSteps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  faqsHeading?: T;
  faqs?: T;
  finalCtaHeadline?: T;
  finalCtaCopy?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  headline?: T;
  lead?: T;
  body?: T;
  ownerName?: T;
  ownerRole?: T;
  ownerPhoto?: T;
  establishedYear?: T;
  serviceArea?: T;
  credentialsHeading?: T;
  credentials?:
    | T
    | {
        label?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  headline?: T;
  lead?: T;
  formIntro?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-content_select".
 */
export interface LegalContentSelect<T extends boolean = true> {
  privacyPolicy?: T;
  terms?: T;
  disclaimer?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}